version: "3"
networks:
  nacos_default:
    external: true
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ./env/nacos-hostname.env
    restart: on-failure
    external_links:
      - mysql5.7:mysql
    networks:
      - nacos_default
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:latest
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
    env_file:
      - ./env/nacos-hostname.env
    restart: on-failure
    external_links:
      - mysql5.7:mysql
    networks:
      - nacos_default
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:latest
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8850:8848"
    env_file:
      - ./env/nacos-hostname.env
    restart: on-failure
    external_links:
      - mysql5.7:mysql
    networks:
      - nacos_default
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-cluster.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos1
      - nacos2
      - nacos3
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
        - 3000:3000
    restart: on-failure
